[package]
name = "protoshark"
version = "1.0.0"
authors = ["KingRainbow44"]
description = "Utilities for Google's Protocol Buffers schema"
edition = "2021"

[dependencies]

paste = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]

serde_json = "1"