[package]
name = "protoshark"
version = "0.1.0"
authors = ["KingRainbow44"]
description = "Arbitrary decoder for protobuf3"
edition = "2021"

[dependencies]

paste = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]

serde_json = "1"